const reviews = [
    {
        id: 1,
        name: "Alain Flamand",
        job: "Web Developer",
        img: "images/Alain Flamand.jpeg",
        text: "I wasn’t sure what to expect at first, but the entire experience turned out to be amazing. From the moment I reached out, I was treated with respect and professionalism. Every step of the process was clearly explained, and the results were far beyond what I imagined. The team showed genuine care and delivered everything right on time. I felt supported, understood, and valued throughout. It’s rare to find service like this anymore. Truly a wonderful experience.",
    },
    {
        id: 2,
        name: "Andrew E. Williams",
        job: "Software Developer",
        img: "images/Andrew E. Williams.jpeg",
        text: "Honestly, I’m not someone who usually writes reviews, but I had to this time. The way everything was handled from start to finish was just perfect. Communication was consistent, the attention to detail was outstanding, and I felt like my needs were truly prioritized. I’ve dealt with many companies before, but none left such a strong positive impression on me. I would absolutely return again without hesitation. This is the standard everyone should follow.",
    },
    {
        id: 3,
        name: "Antoine Beauchamps",
        job: "Chef",
        img: "images/Antoine Beauchamps.jpeg",
        text: "It’s hard to describe how easy and smooth everything went. I reached out, not really expecting much, but I was pleasantly surprised by the level of service and care. Every question I had was answered quickly and thoroughly. The team was knowledgeable, kind, and truly seemed to care about doing a good job. I never once felt rushed or dismissed, which made all the difference. This experience restored a bit of my faith in customer service. Highly recommended.",
    },
    {
        id: 4,
        name: "Bartlett Hébert",
        job: "Journalist",
        img: "images/Bartlett Hébert.jpeg",
        text: "From the very first interaction, I could tell this was going to be different. The professionalism, kindness, and overall efficiency blew me away. I appreciated how transparent everything was—no hidden fees, no confusing steps, just honesty and quality work. Everything was delivered as promised, and even a little bit more. I felt like a priority the entire time. It’s rare to find such consistency, and I’m genuinely grateful for how things turned out.",
    },
    {
        id: 5,
        name: "Eric Lowe",
        job: "Accountant",
        img: "images/Eric Lowe.jpeg",
        text: "I’ve worked with a lot of companies over the years, and very few have stood out the way this one did. Every person I interacted with was knowledgeable and patient. I had a lot of questions and concerns, but they never made me feel like a burden. The quality of the final result was absolutely top-notch, and the process was surprisingly enjoyable. I was expecting stress, but got peace of mind instead. I wouldn’t hesitate to recommend them to anyone.",
    },
    {
        id: 6,
        name: "Geoffrey Chaussée",
        job: "Architect",
        img: "images/Geoffrey Chaussée.jpeg",
        text: "At first, I wasn’t sure if this was going to be the right choice. But from day one, I was impressed. The team was organized, helpful, and clearly passionate about what they do. They explained things in simple terms, respected my time, and delivered exactly what I needed. It was one of the most seamless experiences I’ve had in a long time. Everything was handled with care, and that made all the difference. I wouldn’t go anywhere else after this.",
    },
    {
        id: 7,
        name: "Megan R. Hoch",
        job: "Nurse",
        img: "images/Megan R. Hoch.jpeg",
        text: "This was one of those rare experiences where everything just worked. No delays, no excuses—just clear, honest communication and high-quality results. Every interaction I had felt personal and intentional, not just some copy-paste response. The people behind the scenes really seem to care, and that’s reflected in the final outcome. I’ve already recommended it to a few friends because I trust others will have the same great experience I did.",
    },
    {
        id: 8,
        name: "Odette Lamarre",
        job: "Teacher",
        img: "images/Odette Lamarre.jpeg",
        text: "I don’t usually leave detailed reviews, but this experience deserves recognition. I felt heard, respected, and well taken care of every step of the way. They were attentive to my needs and went above and beyond to ensure everything was perfect. Every little detail was handled with precision and care. In today’s world, where most things feel rushed or automated, this level of human touch really stands out. I’m incredibly happy with the outcome.",
    },
    {
        id: 9,
        name: "Thomas LeBatelier",
        job: "Photographer",
        img: "images/Thomas LeBatelier.jpeg",
        text: "It’s not every day you come across a team that genuinely delivers more than expected. I appreciated how quickly they responded to my questions and how they stayed in touch throughout the entire process. There was never a moment of confusion or uncertainty. Everything was handled with transparency and confidence. They made sure I was comfortable with every decision. This is how it should be done, and I’m thankful I chose to work with them.",
    },
    {
        id: 10,
        name: "Valentine Tessier",
        job: "Marketing Specialist",
        img: "images/Valentine Tessier.jpeg",
        text: "I can honestly say this was one of the smoothest processes I’ve ever been part of. The people were friendly, professional, and incredibly efficient. They communicated clearly and stayed consistent throughout. There was no guesswork—I always knew what was happening and what to expect. That kind of clarity is rare these days. I walked away not just satisfied, but actually happy. I didn’t think I’d enjoy the process, but it turned out great.",
    },
    {
        id: 11,
        name: "William Desaulniers",
        job: "Mechanical Engineer",
        img: "images/William Desaulniers.jpeg",
        text: "From the start, everything felt different—in a good way. The process was so organized and clear that I didn’t once feel overwhelmed. They kept me informed the whole time and made sure every part of the experience was stress-free. Their attention to detail and patience really stood out. I was honestly surprised at how simple they made everything seem. I came in with doubts, but I left feeling confident and satisfied. I’d absolutely do this again.",
    },
    {
        id: 12,
        name: "Zara Proulx",
        job: "Data Analyst",
        img: "images/Zara Proulx.jpeg",
        text: "If I could give more than five stars, I would. Everything was handled with care, speed, and precision. I never felt like just another customer. Every interaction felt personal, and I always had someone available to help me if I needed. They answered my questions before I even had to ask. That kind of attentiveness is rare and deserves praise. The final result exceeded what I had imagined. I’ll be recommending this experience to everyone I know.",
    }
];